name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push backend
      run: |
        cd backend
        gcloud builds submit --pack image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend || true

    - name: Build and push frontend
      run: |
        cd frontend
        gcloud builds submit --pack image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend || true


    - name: Deploy backend
      run: |
        gcloud run deploy backend \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend \
        --region us-central1 \
        --allow-unauthenticated \
        --platform managed

    - name: Deploy frontend
      run: |
        gcloud run deploy frontend \
        --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend \
        --region us-central1 \
        --allow-unauthenticated \
        --platform managed
